import { Product } from './types';

export const seedProducts: Omit<Product, 'id' | 'createdAt'>[] = [
    // ─── Women's ─────────────────────────────────────────
    {
        name: 'Bridal Lehenga — Royal Maroon',
        description: 'Heavy embroidered velvet lehenga with zari work & dupatta.',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=2574&auto=format&fit=crop',
        price: 15000,
        discountedPrice: 12000,
        category: 'women',
        tag: 'Bestseller',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Reception Gown — Champagne Gold',
        description: 'Floor-length gown with sequin bodice and flowing trail.',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=2574&auto=format&fit=crop',
        price: 12000,
        category: 'women',
        tag: 'New Arrival',
        inventory: 2,
        isActive: true,
    },
    {
        name: 'Sangeet Lehenga — Emerald Green',
        description: 'Lightweight lehenga choli with mirror work for sangeet night.',
        image: 'https://images.unsplash.com/photo-1585994235881-228d4ddb59c5?q=80&w=2574&auto=format&fit=crop',
        price: 8000,
        discountedPrice: 6500,
        category: 'women',
        tag: 'Trending',
        inventory: 4,
        isActive: true,
    },
    {
        name: 'Mehendi Outfit — Sunshine Yellow',
        description: 'Vibrant yellow sharara set with floral embroidery.',
        image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=2574&auto=format&fit=crop',
        price: 6000,
        category: 'women',
        tag: 'Popular',
        inventory: 5,
        isActive: true,
    },
    {
        name: 'Nauvari Saree — Traditional Nine Yards',
        description: 'Classic Maharashtrian Nauvari in pure silk with temple border.',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=2574&auto=format&fit=crop',
        price: 5000,
        category: 'women',
        tag: 'Heritage',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Paithani Saree — Peacock Motif',
        description: 'Handwoven Paithani with gold zari and peacock pallu.',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=2574&auto=format&fit=crop',
        price: 7000,
        discountedPrice: 5500,
        category: 'women',
        tag: 'Premium',
        inventory: 2,
        isActive: true,
    },

    // ─── Men's ───────────────────────────────────────────
    {
        name: 'Wedding Sherwani — Ivory & Gold',
        description: 'Classic ivory sherwani with intricate gold threadwork and matching stole.',
        image: 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?q=80&w=2680&auto=format&fit=crop',
        price: 10000,
        discountedPrice: 8000,
        category: 'men',
        tag: 'Bestseller',
        inventory: 4,
        isActive: true,
    },
    {
        name: 'Jodhpuri Suit — Midnight Blue',
        description: 'Tailored Jodhpuri bandhgala in rich midnight blue with velvet collar.',
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=2574&auto=format&fit=crop',
        price: 8000,
        category: 'men',
        tag: 'New Arrival',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Indo-Western — Charcoal Black',
        description: 'Contemporary Indo-Western ensemble with asymmetric jacket and kurta.',
        image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=2574&auto=format&fit=crop',
        price: 7000,
        category: 'men',
        tag: 'Trending',
        inventory: 5,
        isActive: true,
    },
    {
        name: 'Reception Tuxedo — Classic Black',
        description: 'Sharp tailored tuxedo with satin lapels and bow-tie set.',
        image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=2580&auto=format&fit=crop',
        price: 12000,
        discountedPrice: 9500,
        category: 'men',
        tag: 'Premium',
        inventory: 2,
        isActive: true,
    },
    {
        name: 'Designer Jacket — Royal Maroon',
        description: 'Embroidered velvet jacket paired with silk kurta and churidar.',
        image: 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?q=80&w=2680&auto=format&fit=crop',
        price: 6000,
        category: 'men',
        tag: 'Popular',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Sangeet Kurta — Pastel Sage',
        description: 'Relaxed-fit silk kurta set with subtle embroidery for sangeet night.',
        image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=2574&auto=format&fit=crop',
        price: 4000,
        category: 'men',
        tag: 'New',
        inventory: 6,
        isActive: true,
    },

    // ─── Jewellery ───────────────────────────────────────
    {
        name: 'AD Stone Bridal Set',
        description: 'Complete bridal set with necklace, earrings, maang tikka, and bangles in American Diamond.',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=2574&auto=format&fit=crop',
        price: 5000,
        discountedPrice: 4000,
        category: 'jewellery',
        tag: 'Bestseller',
        inventory: 5,
        isActive: true,
    },
    {
        name: 'South Indian Temple Set',
        description: 'Traditional gold-plated temple jewellery with Lakshmi coin motifs and kemp stones.',
        image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?q=80&w=2574&auto=format&fit=crop',
        price: 6000,
        category: 'jewellery',
        tag: 'Heritage',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Kundan Bridal Necklace',
        description: 'Royal Kundan choker with matching jhumkas and haath phool.',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=2574&auto=format&fit=crop',
        price: 8000,
        discountedPrice: 6500,
        category: 'jewellery',
        tag: 'Premium',
        inventory: 2,
        isActive: true,
    },
    {
        name: 'Maharashtrian Nath & Thushi',
        description: 'Traditional Maharashtrian nose ring set with Thushi choker and mohan maal.',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=2574&auto=format&fit=crop',
        price: 3500,
        category: 'jewellery',
        tag: 'Traditional',
        inventory: 4,
        isActive: true,
    },
    {
        name: 'Pearl & Polki Set',
        description: 'Elegant pearl strings with polki pendant set for reception or engagement.',
        image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?q=80&w=2574&auto=format&fit=crop',
        price: 4500,
        category: 'jewellery',
        tag: 'Elegant',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Statement Earrings Collection',
        description: 'Mix of chandbali, jhumka, and contemporary statement earrings.',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=2574&auto=format&fit=crop',
        price: 2000,
        category: 'jewellery',
        tag: 'New Arrival',
        inventory: 8,
        isActive: true,
    },

    // ─── Photoshoots ─────────────────────────────────────
    {
        name: 'Pre-Wedding Couple Set',
        description: 'Coordinated outfits for pre-wedding photoshoots — lehenga + sherwani in matching tones.',
        image: 'https://images.unsplash.com/photo-1627931383796-f942125fc832?q=80&w=2574&auto=format&fit=crop',
        price: 18000,
        discountedPrice: 14000,
        category: 'photoshoots',
        tag: 'Most Popular',
        inventory: 2,
        isActive: true,
    },
    {
        name: 'Maternity Gown — Blush Pink',
        description: 'Flowing chiffon maternity gown with off-shoulder design, perfect for dreamy shoots.',
        image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=2574&auto=format&fit=crop',
        price: 5000,
        category: 'photoshoots',
        tag: 'Trending',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Baby Shower Outfit — Mint Green',
        description: 'Elegant mint green anarkali set with dupatta for the mommy-to-be.',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=2574&auto=format&fit=crop',
        price: 4000,
        category: 'photoshoots',
        tag: 'New Arrival',
        inventory: 4,
        isActive: true,
    },
    {
        name: 'Bride & Groom Matching Set',
        description: 'Colour-coordinated bridal lehenga and sherwani set for wedding day or reception.',
        image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=2574&auto=format&fit=crop',
        price: 20000,
        discountedPrice: 16000,
        category: 'photoshoots',
        tag: 'Premium',
        inventory: 2,
        isActive: true,
    },
    {
        name: 'Engagement Outfit — Dusty Rose',
        description: 'Soft dusty rose lehenga with delicate pearl work for intimate engagement ceremonies.',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=2574&auto=format&fit=crop',
        price: 9000,
        discountedPrice: 7500,
        category: 'photoshoots',
        tag: 'Bestseller',
        inventory: 3,
        isActive: true,
    },
    {
        name: 'Fantasy Theme Gown — Ethereal White',
        description: 'Floor-length white gown with dramatic trail for editorial or fantasy-themed shoots.',
        image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=2574&auto=format&fit=crop',
        price: 7000,
        category: 'photoshoots',
        tag: 'Editorial',
        inventory: 2,
        isActive: true,
    },
];
